import { Texture } from './Texture';
import { ItemId } from './ItemId';
import { TileT } from '../types/TileT';

export const MAP: TileT[] = [
    {
        id: 'tile-0-0',
        textures: [Texture.Grass],
        position: [0, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-0-1',
        textures: [Texture.Grass],
        position: [0, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-0-2',
        textures: [Texture.Wall],
        position: [0, 2],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-0-3',
        textures: [Texture.Grass],
        position: [0, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-0-4',
        textures: [Texture.Grass],
        position: [0, 4],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-0-5',
        textures: [Texture.Grass],
        position: [0, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-1-0',
        textures: [Texture.Grass],
        position: [1, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-1-1',
        textures: [Texture.Grass],
        position: [1, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-1-2',
        textures: [Texture.Wall],
        position: [1, 2],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-1-3',
        textures: [Texture.Grass],
        position: [1, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-1-4',
        textures: [Texture.Grass],
        position: [1, 4],
        isBlockade: false,
        items: [{ id: 'turnip-1', itemId: ItemId.Turnip }],
    },
    {
        id: 'tile-1-5',
        textures: [Texture.Grass],
        position: [1, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-2-0',
        textures: [Texture.Grass],
        position: [2, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-2-1',
        textures: [Texture.Grass],
        position: [2, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-2-2',
        textures: [Texture.Grass],
        position: [2, 2],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-2-3',
        textures: [Texture.Grass],
        position: [2, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-2-4',
        textures: [Texture.Grass],
        position: [2, 4],
        isBlockade: false,
        items: [{ id: 'turnip-2', itemId: ItemId.Turnip }],
    },
    {
        id: 'tile-2-5',
        textures: [Texture.Grass],
        position: [2, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-3-0',
        textures: [Texture.Grass],
        position: [3, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-3-1',
        textures: [Texture.Grass],
        position: [3, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-3-2',
        textures: [Texture.Wall],
        position: [3, 2],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-3-3',
        textures: [Texture.Grass],
        position: [3, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-3-4',
        textures: [Texture.Grass],
        position: [3, 4],
        isBlockade: false,
        items: [{ id: 'turnip-3', itemId: ItemId.Turnip }],
    },
    {
        id: 'tile-3-5',
        textures: [Texture.Grass],
        position: [3, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-4-0',
        textures: [Texture.Wall],
        position: [4, 0],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-4-1',
        textures: [Texture.Wall],
        position: [4, 1],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-4-2',
        textures: [Texture.Wall],
        position: [4, 2],
        isBlockade: true,
        items: [],
    },
    {
        id: 'tile-4-3',
        textures: [Texture.Grass],
        position: [4, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-4-4',
        textures: [Texture.Grass],
        position: [4, 4],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-4-5',
        textures: [Texture.Grass],
        position: [4, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-0',
        textures: [Texture.Grass],
        position: [5, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-1',
        textures: [Texture.Grass],
        position: [5, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-2',
        textures: [Texture.Grass],
        position: [5, 2],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-3',
        textures: [Texture.Grass],
        position: [5, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-4',
        textures: [Texture.Grass],
        position: [5, 4],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-5-5',
        textures: [Texture.Grass],
        position: [5, 5],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-0',
        textures: [Texture.Grass],
        position: [6, 0],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-1',
        textures: [Texture.Grass],
        position: [6, 1],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-2',
        textures: [Texture.Grass],
        position: [6, 2],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-3',
        textures: [Texture.Grass],
        position: [6, 3],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-4',
        textures: [Texture.Grass],
        position: [6, 4],
        isBlockade: false,
        items: [],
    },
    {
        id: 'tile-6-5',
        textures: [Texture.Grass],
        position: [6, 5],
        isBlockade: false,
        items: [],
    },
];
